"""Create Task model with Priority and Status enums, comprehensive fields, and indexes

Revision ID: b5a72e6fd467
Revises: 
Create Date: 2025-09-24 08:01:42.650042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a72e6fd467'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_task_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_status', table_name='tasks')
    op.drop_index('idx_task_priority', table_name='tasks')
    op.drop_index('idx_task_due_date', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
